#!/bin/bash

git status

read -p "What needs to be checked? " CHECKER
echo $CHECKER
wait
echo "Running puppet-lint"

if ! puppet-lint --error-level error . ; then
  echo "Something isn't right"
  exit 1
else
  echo "Looks good"
  exit 0
fi
